[package]
name = "mothrbox"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = {version = "0.13.0", features = ["ecdh"]}
aes-gcm =  { version = "0.10", features = ["std"] }
rand = "0.8"
sha2 = "0.10" 
hex = "0.4"
rayon = "1.10.0"
anyhow = "1.0"