[package]
name = "mothrbox"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = {version = "0.13.0", features = ["ecdh"]}
aes-gcm = "0.10.1"
rand_core = "0.9.3"
rand = "0.9.0"
sha2 = "0.10.6" 
hex = "0.4.3"
rayon = "1.10.0"
